runtime: python37

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
- url: /favicon\.png
  static_files: static/favicon.png
  upload: static/favicon\.png
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
- url: /.*
  script: auto
